--------------------------------------------------------
--  File created - Wednesday-December-21-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_WORK_ORDER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TBL_WORK_ORDER" 
   (	"WRK_ODR_SLNO" NUMBER, 
	"EMP_NAME" VARCHAR2(40 BYTE), 
	"TIME_IN" VARCHAR2(10 BYTE), 
	"TIME_OUT" VARCHAR2(10 BYTE), 
	"WORKED_HRS" VARCHAR2(10 BYTE), 
	"CREATED_BY" VARCHAR2(30 BYTE), 
	"CREATED_DATE" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.TBL_WORK_ORDER
SET DEFINE OFF;
Insert into SYSTEM.TBL_WORK_ORDER (WRK_ODR_SLNO,EMP_NAME,TIME_IN,TIME_OUT,WORKED_HRS,CREATED_BY,CREATED_DATE) values (12,'rajesh555','9.30','10.30','1.00','rajesh555',to_date('15-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_WORK_ORDER (WRK_ODR_SLNO,EMP_NAME,TIME_IN,TIME_OUT,WORKED_HRS,CREATED_BY,CREATED_DATE) values (1,'ABC','09.30','06.30','09.00','SYSTEM',to_date('09-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_WORK_ORDER (WRK_ODR_SLNO,EMP_NAME,TIME_IN,TIME_OUT,WORKED_HRS,CREATED_BY,CREATED_DATE) values (10,'rajesh555','9.30','10.30','1.10','rajesh555',to_date('13-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_WORK_ORDER (WRK_ODR_SLNO,EMP_NAME,TIME_IN,TIME_OUT,WORKED_HRS,CREATED_BY,CREATED_DATE) values (11,'kkk','9.30','10.30','1.00','kkk',to_date('15-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_WORK_ORDER (WRK_ODR_SLNO,EMP_NAME,TIME_IN,TIME_OUT,WORKED_HRS,CREATED_BY,CREATED_DATE) values (13,'rajesh555','9.30','10.30','1.00','rajesh555',to_date('15-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_WORK_ORDER (WRK_ODR_SLNO,EMP_NAME,TIME_IN,TIME_OUT,WORKED_HRS,CREATED_BY,CREATED_DATE) values (14,'rajesh555','9.30','10.30','1.00','rajesh555',to_date('15-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_WORK_ORDER (WRK_ODR_SLNO,EMP_NAME,TIME_IN,TIME_OUT,WORKED_HRS,CREATED_BY,CREATED_DATE) values (15,'rajesh555','9.30','10.30','1.00','rajesh555',to_date('15-12-16','DD-MM-RR'));
