--------------------------------------------------------
--  File created - Wednesday-December-21-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_USER_REGISTRATION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TBL_USER_REGISTRATION" 
   (	"EMP_SRL_NUM" NUMBER, 
	"USER_NAME" VARCHAR2(30 BYTE), 
	"USER_PASSWORD" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(45 BYTE), 
	"MOBILE" NUMBER, 
	"USER_ROLE" VARCHAR2(20 BYTE), 
	"CREATED_BY" VARCHAR2(25 BYTE), 
	"CREATED_DATE" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.TBL_USER_REGISTRATION
SET DEFINE OFF;
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (4,'mmmm11','sss11','mmm@gamil.com',9874561231,'ADMIN','mmmm11',to_date('09-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (5,'mmmm22','sss22','mmm@gamil.com',9874561231,'ADMIN','mmmm22',to_date('13-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (6,'MSUSER','MSUSER','mmm@gamil.com',9003354499,'USER','MSUSER',to_date('13-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (7,'drip','star','mmm@gamil.com',9003354499,'USER','drip',to_date('13-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (12,'driyt','staras','mmm@gamil.com',9003354499,'USER','driyt',to_date('13-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (14,'driytsds','starasad','mmm@gamil.com',9003354499,'USER','driytsds',to_date('13-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (15,'test1234','test1234','mmmghhj@gamil.com',90037899,'USER','test1234',to_date('13-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (16,'adddmin','adddmin','addsd@gmail.com',123456,'Employee','adddmin',to_date('13-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (17,'adddddminasdasdas','addddddmdasdasdasin','adddddsd@gmail.com',123456,'Employee','adddddminasdasdas',to_date('13-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (21,'rajesh','raji','sss@gamil.com',1234568889,'ADMIN','rajesh',to_date('13-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (1,'ABC','ABC@123','ABC@TECHMAHINDRA.COM',9963599635,'ADMIN','SYSTEM',to_date('09-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (3,'mmmm','sss','mmm@gamil.com',9874561231,'ADMIN','mmmm',to_date('09-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (23,'mmmm2244','sss2244','mmm@gamil.com',9874561231,'ADMIN','mmmm2244',to_date('13-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (24,'mmmm22445522','sss224466611','mmm@gamil.com',9874561231,'ADMIN','mmmm22445522',to_date('14-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (25,'abc','sss','mmm@gamil.com',9874561231,'ADMIN','abc',to_date('14-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (33,'abcd','ssss','mmn@gamil.com',9874561232,'ADMIN','abcd',to_date('14-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (36,'bbc','tss','nmm@gamil.com',8874561231,'ADMIN','bbc',to_date('14-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (37,'hhh','uuuu','mmm@gamil.com',9874561231,'ADMIN','hhh',to_date('14-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (47,'brahmam','s334','mmm@gamil.com',9874561231,'ADMIN','brahmam',to_date('15-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (52,'admin456','admin','admin456@gmail.com',45564654,'admin','admin456',to_date('15-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (53,'gttty','e4tettr','dr@gggg.com',67567589,'nghtujy','gttty',to_date('15-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (55,'fdgfg','frtgdfg','dr@bkhjh.com',4444444444,'USER','fdgfg',to_date('15-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (59,'Alam','$welcom123','ma00487542@techmahindra.com',8220860146,'admin','Alam',to_date('15-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (62,'mmmm2248','sss2244','mmm@gamil.com',9874561231,'ADMIN','mmmm2248',to_date('15-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (81,'mahesh','mah@123','mkreddygtm@gmail.com',1234567894,'ADMIN','mahesh',to_date('15-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (82,'kiran','kir@123','scbsupport@scbdom.com',1234567894,'ADMIN','kiran',to_date('16-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (83,'meee123','meee123','mee@gmail.com',1442345678,'admin','meee123',to_date('16-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (84,'rajesh555','raji','sss@gamil.com',1234568889,'ADMIN','rajesh555',to_date('16-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (85,'kiran11','kir11@123','scbsupport@scbdom.com',1234567894,'ADMIN','kiran11',to_date('19-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (89,'bbc11','bbcpwd11','vvvgggg@gamil.com',98745644443,'ADMIN','bbc11',to_date('20-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (90,'alagu','alagu','alagu@gmail',9003354488,'admin','alagu',to_date('21-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (91,'alagu11','alagu11','ala@gmn',52226,'admin','alagu11',to_date('21-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (92,'alagu22','alagu22','ala@gmn',52226,'admin','alagu22',to_date('21-12-16','DD-MM-RR'));
Insert into SYSTEM.TBL_USER_REGISTRATION (EMP_SRL_NUM,USER_NAME,USER_PASSWORD,EMAIL,MOBILE,USER_ROLE,CREATED_BY,CREATED_DATE) values (98,'alagu2222','alagu2222','ala@gmnfgg',5222226,'admin22','alagu2222',to_date('21-12-16','DD-MM-RR'));
--------------------------------------------------------
--  DDL for Index EMP_SRL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."EMP_SRL_PK" ON "SYSTEM"."TBL_USER_REGISTRATION" ("EMP_SRL_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ENAME_UNQ_CONS
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ENAME_UNQ_CONS" ON "SYSTEM"."TBL_USER_REGISTRATION" ("USER_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TBL_USER_REGISTRATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TBL_USER_REGISTRATION" ADD CONSTRAINT "ENAME_UNQ_CONS" UNIQUE ("USER_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."TBL_USER_REGISTRATION" ADD CONSTRAINT "EMP_SRL_PK" PRIMARY KEY ("EMP_SRL_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."TBL_USER_REGISTRATION" MODIFY ("USER_ROLE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_USER_REGISTRATION" MODIFY ("MOBILE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_USER_REGISTRATION" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_USER_REGISTRATION" MODIFY ("USER_PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_USER_REGISTRATION" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TBL_USER_REGISTRATION" MODIFY ("EMP_SRL_NUM" NOT NULL ENABLE);
